### ISSUE TITLE
Version 1.1 Release Checklist

### ISSUE THREAD

**Issue by jatinchowdhury18** [Chowdhury-DSP/ChowMatrix#35]
- [x] Testing
    - [x] Ableton (Win64)
    - [x] Ableton (Win32)
    - [x] Reaper
    - [x] FL Studio
    - [x] Ableton (Mac)
    - [x] Logic Pro
    - [x] Garageband
- [x] Close out remaining issues for v1.1 Milestone
- [x] Update Docs:
    - [x] Update Changelog
    - [x] Update screenshots
    - [x] Update User Manual
    - [x] Update README
- [x] Create Release:
   - [x] Generate builds
   - [x] Merge `develop` branch into `main`
   - [x] Tag a GitHub Release
- [x] Announce:
    - [x] Update KVR
    - [x] Post on Patreon
    - [x] Post a demo video on YouTube...
