### ISSUE TITLE
1.2.0 Release Checklist

### ISSUE THREAD

**Issue by jatinchowdhury18** [Chowdhury-DSP/ChowMatrix#86]
- [x] Close out all other tickets
- [x] Update User Manual
- [x] Update Screenshots
- [x] Bump version number
- [x] Update README, CHANGELOG, etc.
- [x] Generate release builds/installers
- [x] Merge to master
- [x] Tag GitHub Release
- [x] Update website
- [x] Update user manual
- [x] Postings:
  - [x] KVR
  - [x] Webpage (news)
  - [x] Patreon
